### ISSUE TITLE
Reproduction Biased MNIST from Table 1

### ISSUE THREAD

**Issue by alexrame** [erobic/bias-mitigators#2]
Thank you for your nice work and code.
My question is: could you provide the necessary roadmaps/commands to reproduce the Biased MNIST results from Table 1 (and Table A4) ?

First, it seems like we need to create the dataset as the dataset provided in as provided in your google drive: https://drive.google.com/drive/folders/1O5aUB-egT613oGmm2q01EuXpxjXjjwRd is not exactly the one needed.
* in full_generator.sh, we need to set p_bias=0.7 instead of 0.95, correct ? 
* What is the appropriate yaml file for this dataset creation: indeed colored_mnist.yaml only has 6 bias enabled (digit_color,digit_position,texture,texture_color,letter,letter_color): so which is the seventh missing ? Moreover, how do you match these bias names with those defined in Table A4: distractor shape=letter, distractor color=letter_color?, background color = ?

Second, which commands should we run to launch the experiments? In particular, when running bias-mitigators/scripts/biased_mnist/baseline_biased_mnist.sh, the experiment "biased_mnist_experiments" is not defined. Moreover, in explicit methods such as IRM, '--expt_type biased_mnist_experiments_hierarchical' matches to an experiment with several explicit biases (similar to Table A5). I speculate that the appropriate experiment for Table1/A4 method should be something like:
```
list_biases = ["digit_color","digit_position","texture","texture_color","letter","letter_color", "background_color?"]
def biased_mnist_experiments_table1_explicitmethods(option, run_fn):
    # Here, we configure rest of the arguments which likely DO NOT NEED TO BE CHANGED
    for bias_variable in list_biases:
        run_expt(copy.deepcopy(option), run_fn, 0.7, [bias_variable], '')
```

Then, which metrics should we focus on? As you are reporting the Acc(alpha=0), I speculate it's the "Mean Per group_name" in the logs. And then I believe I need to average those means for each explicit bias ?

Thanks in advance,
Alexandre

**Comment by erobic** [comment]
Hi @alexrame,

Sorry for all of the confusion. Actually, we decided to create a new version of BiasedMNIST and decided to run experiments with ResNet-10 (instead of the small architecture used originally in the paper). I plan on updating the paper with the new results next week.

For now, I hope the following answers will help, and I will notify you once the paper is updated:
- `full_generator.sh` uses `full_v1.yaml`, which has 6 bias variables. We will update the paper with only those variables.
- The exact command will depend on the bias variables and the level of p_bias to be considered. I added the `biased_mnist_experiments` experiment. This is the default experiment with p_bias = 0.95, single explicit bias = digit_color.
- For BiasedMNIST, Acc(alpha=0) or unbiased accuracy corresponds to 'Main Accuracy' reported for the test set because the test set is created with p_bias = 0.1 i.e., intended to have a balanced number of groups. We can simply use this instead of further computing mean group accuracies. Another reason we do not compute mean of groups directly is that there are too many possible groups (e.g., with 6 variables, each with 10 possible values, we can create 10^6 unique groups!, which just won't be covered in the test set anyway).
- We can get these metrics, from the sample log shown below

**Metrics:**
> Acc(alpha=0) = Unbiased Acc = 49.73

> Sample entry for Table A4 based on digit color:
> Digit Color (Majority group accuracy (zzz_digit_color_majority) = 74.3, Minority group accuracy (zzz_digit_color_minority) = 47.0)

**Sample log:**
```Epoch 50: Testing with data split: Test model: Main
2021-06-22 01:07:03,256 - root - INFO - {
    "Main Accuracy": 49.730000000000004,
    "Main MPA": 49.73463516449127,
    "Mean Per digit_color_group_name": 60.67444923792166,
    "Mean Per digit_position_group_name": 52.30609982352142,
    "Mean Per group_name": 49.70510805411111,
    "Mean Per letter_color_group_name": 54.918179446080444,
    "Mean Per letter_group_name": 52.75712207570854,
    "Mean Per maj_min_group_name": 60.67444923792166,
    "Mean Per texture_color_group_name": 52.56872680922274,
    "Mean Per texture_group_name": 62.35012203577515,
    "digit_color_0": 61.154598825831705,
    "digit_color_1": 52.91790306627102,
    "digit_color_2": 39.609756097560975,
    "digit_color_3": 37.372708757637476,
    "digit_color_4": 52.4896265560166,
    "digit_color_5": 53.01810865191147,
    "digit_color_6": 58.78172588832488,
    "digit_color_7": 58.7192118226601,
    "digit_color_8": 47.97230464886251,
    "digit_color_9": 35.01513622603431,
    "digit_color_majority": 74.31749241658241,
    "digit_color_minority": 47.0314060592609,
    "zzz_digit_color_majority": 74.31749241658241,
    "zzz_digit_color_minority": 47.0314060592609,
    "zzz_digit_position_majority": 55.51020408163265,
    "zzz_digit_position_minority": 49.1019955654102,
    "zzz_letter_color_majority": 61.34715025906736,
    "zzz_letter_color_minority": 48.489208633093526,
    "zzz_letter_majority": 56.58021133525456,
    "zzz_letter_minority": 48.93403281616252,
    "zzz_texture_color_majority": 56.14035087719298,
    "zzz_texture_color_minority": 48.997102741252505,
    "zzz_texture_majority": 78.15292949354519,
    "zzz_texture_minority": 46.547314578005114
}
```


Hope these help for now. The scripts will work, but the paper is outdated right now :-(. Please let me know if you have further questions.

**Comment by alexrame** [comment]
Thank you for your quick answer! I get it, hope to read the new version of your paper soon.
Just to be sure, I still need to add
```
def biased_mnist_experiments(option, run):
    # Method-specific arguments are mostly defined in the bash files inside: scripts/celebA
    orig_option = copy.deepcopy(option)

    # Here, we configure rest of the arguments which likely DO NOT NEED TO BE CHANGED
    for bias_variables in [['digit_color']]:
        for p_bias in [0.95]:
            run_expt(orig_option, run, p_bias, bias_variables)
```
in ```experiments/biased_mnist_experiments.py```?

**Comment by erobic** [comment]
Oh, seems like I forgot to push it. Yeah, that's the function/file.

**Comment by alexrame** [comment]
Thanks. Before closing the issue, by any chance, do you have the table of results on this setup for the different approaches?

**Comment by erobic** [comment]
Hi, I will need a bit more time to provide the results. I will let you know once I collect them.

**Comment by erobic** [comment]
Follow up: It will take some more time for me to release the results. I realized that the dataset version I uploaded had an error (the generator had a bug), so am re-running all experiments :-(. I will re-upload the dataset and the results and let you know.

**Comment by erobic** [comment]
I decided to keep the original version of the dataset (as published in WACV 2021) and use the new version in the future.
The dataset is available here: https://drive.google.com/file/d/1RlvskdRjdAj6sqpYeD48sR2uJnxAYmv5/view?usp=sharing
The repo now contains scripts for different methods.
